---
# This playbook deploys the whole application stack on the Jenkins-server.
- name: Setup nginx server
  hosts: nginx
  become: yes

  roles:
    - nginx

  handlers:
    - include: handlers/main.yml

- name: Setup nodes with app
  hosts: nodes
  become: yes

  roles:
    - docker
    - app

  handlers:
    - include: handlers/main.yml
