---
- name: enable_nginx
  service:
    name: nginx
    enabled: yes

- name: start_nginx
  service:
    name: nginx
    state: started

- name: restart_nginx
  service:
    name: nginx
    state: restarted