---
- name: Check if launch script exist in `/etc/systemd/system/`
  stat:
    path: "/etc/systemd/system/infra_app.service"
  register: launch_script_exists_check

- name: Copy launch script template in `/etc/systemd/system/`
  template:
    src: ../src/infra_app.service
    dest: /etc/systemd/system/infra_app.service
    owner: root
    group: root
    mode: 0744
  when: launch_script_exists_check is defined and
        launch_script_exists_check.stat.exists == false

- name: Start app and enable auto launch after reboot
  service:
    name: infra_app
    state: started
    enabled: yes
