---
- name: Copy launch script template in `/etc/systemd/system/`
  template:
    src: ../src/infra_app.service
    dest: /etc/systemd/system/infra_app.service
    owner: root
    group: root
    mode: 0744

- name: Start app and enable auto launch after reboot
  service:
    name: infra_app
    state: started
    enabled: yes
