---
- name: Install packages for apt add repository over HTTPS
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg2
      - curl
      - python3-pip
    state: latest
    update_cache: yes

- name: Add Apt signing key from official docker repo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker official repository for Debian Stretch
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker
  ansible.builtin.package:
    name: docker-ce=5:19.03.15~3-0~debian-stretch
    state: present

- name: Install Docker module for Python (docker_container module dependency)
  pip:
    name: docker
    state: present
